
spring.datasource.url=jdbc:mysql://localhost:3306/finproject_new
spring.datasource.username=root
spring.datasource.password=sent401colt748
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql= true
spring.jpa.hibernate.ddl-auto= update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

logging.level.org.springframework.data.jpa=DEBUG

#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate=DEBUG

kafka.topic.name=transactions-topic




